#!/usr/bin/env php

<?php

use BetasMission\Command\AbstractCommand;

require __DIR__.'/vendor/autoload.php';

/**
 * @return void
 */
function usage()
{
    echo "Available commands : \n";
    echo "\t remove \t - Delete all episodes marked as watched on betaseries\n";
    echo "\t move \t\t - Move the downloaded files into the right show directory\n";
    echo "\t subtitle \t - Download the best subtitle for the episodes, if available\n";
}

$commands = [
    'remove'            => 'BetasMission\Command\RemoveWatchedCommand',
    'move'              => 'BetasMission\Command\MoveCommand',
    'subtitle'          => 'BetasMission\Command\DownloadSubtitleCommand',
    'check-orphan-lock' => 'BetasMission\Command\CheckOrphanLockCommand'
];

$arguments = $argv;

if (count($arguments) == 1 || (isset($arguments[1]) && !array_key_exists($arguments[1], $commands))) {
    usage();

    return -1;
}

/** @var AbstractCommand $command */
$command = new $commands[$arguments[1]]();

if (!$command->preExecute()) {
    return -1;
}

$command->execute();
$command->postExecute();
