#!/usr/bin/env php

<?php

use Command\CommandInterface;

require 'Helper/Autoloader.php';

Helper\Autoloader::register();


/**
 * @return void
 */
function usage()
{
    echo "Available commands : \n";
    echo "\t remove \t - Delete all episodes marked as watched on betaseries\n";
    echo "\t move \t\t - Move the downloaded files into the right show directory\n";
    echo "\t subtitle \t - Download the best subtitle for the episodes, if available\n";
}

$commands = [
    'remove'   => 'Command\RemoveWatchedCommand',
    'move'     => 'Command\MoveCommand',
    'subtitle' => 'Command\DownloadSubtitleCommand'
];

$arguments = $argv;

if (count($arguments) == 1 || (isset($arguments[1]) && !array_key_exists($arguments[1], $commands))) {
    usage();
    return -1;
}

/** @var CommandInterface $command */
$command = new $commands[$arguments[1]]();
$command->execute();
