services:
  betasmission.api_wrapper.betaseries:
    class: BetasMissionBundle\ApiWrapper\BetaseriesApiWrapper
    arguments: ["%betaseries_login%", "%betaseries_password_hash%", "%betaseries_api_key%", "%betaseries_api_base_path%"]

  betasmission.api_wrapper.trakt_tv:
    class: BetasMissionBundle\ApiWrapper\TraktTvApiWrapper
    arguments: ["%trakt_tv_client_id%", "%trakt_tv_client_secret%", "%trakt_tv_api_base_path%", "%trakt_tv_access_token%", "%trakt_tv_refresh_token%", "%trakt_tv_application_pin%"]
