#!/usr/bin/env php

<?php

use BetasMission\Command\AbstractCommand;

require __DIR__.'/vendor/autoload.php';

/**
 * @return void
 */
function usage()
{
    echo "Usage: run ENV COMMAND\n";
    echo "       run --dev subtitle\n\n";
    echo "Env:\n";
    echo "\t--dev    DEV environment\n";
    echo "\t--prod   PROD environment\n\n";
    echo "Commands : \n";
    echo "\t remove               - Delete all episodes marked as watched on betaseries\n";
    echo "\t move                 - Move the downloaded files into the right show directory\n";
    echo "\t subtitle             - Download the best subtitle for the episodes, if available\n";
    echo "\t check-orphan-lock    - Check if a script is locked since a long time\n";
}

$commands = [
    'remove'            => 'BetasMission\Command\RemoveWatchedCommand',
    'move'              => 'BetasMission\Command\MoveCommand',
    'subtitle'          => 'BetasMission\Command\DownloadSubtitleCommand',
    'check-orphan-lock' => 'BetasMission\Command\CheckOrphanLockCommand'
];

$envs = ['--dev', '--prod'];

$arguments = $argv;

if (count($arguments) < 3 || (isset($arguments[2]) && !array_key_exists($arguments[2], $commands)) || (isset($arguments[1]) && !in_array($arguments[1], $envs))) {
    usage();

    return -1;
}

putenv("env=".strtoupper(str_replace('--', '', $arguments[1])));

/** @var AbstractCommand $command */
$command = new $commands[$arguments[2]]();

if (!$command->preExecute()) {
    return -1;
}

$command->execute();
$command->postExecute();
